### PR TITLE
Support UTF16 directly

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
This makes the API easier to use from javascript.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
@robrix If you're using `ts_document_set_input_string`, that API hasn't changed; it still expects a UTF8 string. But the more general `ts_document_set_input` function now allows you to specify either UTF8 or UTF16 as the encoding.

**Comment by robrix** [comment]
:+1: Yeah, wasn’t thinking it’d break us, but more that we have an extra strategy available for handling UTF16 inputs.

**Comment by maxbrunsfeld** [comment]
Ah, sorry for misconstruing. Yeah, If UTF16 support is useful for you guys, let me know if you think we should add an `encoding` argument to `set_input_string` as well.

**Pull request merged**
